Statements pdf download
femueller/python-n26 pull request #102
Opened 2021-04-05 19:13 UTC by AkaTenshi

Hello,
since the statements-command already retrieves the urls of the statements I added an option to download these pdfs as well. Simply supply a directory via the '--download'-option to the statements-command and each statement gets saved there as separate pdf-file. Additionally there are some new options to filter statements by id or date. Useful if you just want to list / download a subset of the statements. The changes are fully backwards-compatible.
My plan with this is to grab last months statement via cronjob or so (for archival purposes). Maybe this is useful to someone else as well. Or you can somehow merge this with the existing feature/show-statement branch :)

2021-04-06 08:46 UTC, femueller commented
Hey @AkaTenshi,

I really like the idea about using the CLI for archiving statements and will look most likely at some point this week more in detail into the PR code.

Thanks for your improvement suggestion! :)

2021-04-09 16:00 UTC, markusressel requested changes
Thx for the PR! Looks very good already, just a couple small things to change. After merge I will create a new Issue for the "better CLI output" stuff.

2021-04-17 00:04 UTC, markusressel commented on n26/api.py
> +                    json: dict = None, headers: dict = None, to_json: bool = True) -> list or dict or None:
I removed this parameter, its not needed since we can use the `Content-Type` header to determine whether we should parse the reponse to json or not.

2021-04-17 00:07 UTC, markusressel approved these changes

2021-04-18 19:15 UTC, femueller commented
Looks good to me :+1:

2021-04-18 19:41 UTC, merged